Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Data;


namespace OnlineSchoolWebApp.Controllers
{

    [Authorize(Roles = "Admin")]
    //[Authorize(Roles = "Admin,Student")]
    public class AppRolesController : Controller

    {
        private readonly RoleManager<IdentityRole> administrateur;
        public AppRolesController(RoleManager<IdentityRole> administrateur)
        {
            this.administrateur = administrateur;
        }

        public IActionResult Index()
        {
            var roles = administrateur.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            //Avoid duplicated roles in our application
            if (!administrateur.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                administrateur.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineSchoolWebApp.Data;
using OnlineSchoolWebApp.Models;

namespace OnlineSchoolWebApp.Controllers
{
    public class CoursController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cours
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cours.Include(c => c.Classe);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Cours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cours == null)
            {
                return NotFound();
            }

            var cours = await _context.Cours
                .Include(c => c.Classe)
                .FirstOrDefaultAsync(m => m.CoursId == id);
            if (cours == null)
            {
                return NotFound();
            }

            return View(cours);
        }


        public async Task<List<ApplicationUser>> DisplayTeachers()
        {
            var roleId = await _context.Roles
                .Where(r => r.Name == "Teacher")
                .Select(r => r.Id)
                .FirstOrDefaultAsync();

            if (roleId == null)
            {
               
            }

            var userIds = await _context.UserRoles
                .Where(ur => ur.RoleId == roleId)
                .Select(ur => ur.UserId)
                .ToListAsync();

            var teachers = await _context.Users
                .OfType<ApplicationUser>()
                .Where(u => userIds.Contains(u.Id))
                .Select(u => new ApplicationUser
                {
                    Id = u.Id, 
                    FirstName = u.FirstName,
                    LastName = u.LastName
                })
                .ToListAsync();

            return teachers;
        }

        // GET: Cours/Create


        public async Task<IActionResult> Create()
        {
            ViewData["ClasseId"] = new SelectList(_context.Classe, "ClasseId", "Nom");
            var teachers = await DisplayTeachers();
            ViewData["EnseignantId"] = new SelectList(teachers, "Id", "LastName");
            return View();
        }

        // POST: Cours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CoursId,Nom,ClasseId,EnseignantId")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cours);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClasseId"] = new SelectList(_context.Classe, "ClasseId", "ClasseId", cours.ClasseId);
            return View(cours);
        }

        // GET: Cours/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cours == null)
            {
                return NotFound();
            }

            var cours = await _context.Cours.FindAsync(id);
            if (cours == null)
            {
                return NotFound();
            }
            ViewData["ClasseId"] = new SelectList(_context.Classe, "ClasseId", "ClasseId", cours.ClasseId);
            return View(cours);
        }

        // POST: Cours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CoursId,Nom,ClasseId,EnseignantId")] Cours cours)
        {
            if (id != cours.CoursId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cours);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoursExists(cours.CoursId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClasseId"] = new SelectList(_context.Classe, "ClasseId", "ClasseId", cours.ClasseId);
            return View(cours);
        }

        // GET: Cours/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cours == null)
            {
                return NotFound();
            }

            var cours = await _context.Cours
                .Include(c => c.Classe)
                .FirstOrDefaultAsync(m => m.CoursId == id);
            if (cours == null)
            {
                return NotFound();
            }

            return View(cours);
        }

        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cours == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cours'  is null.");
            }
            var cours = await _context.Cours.FindAsync(id);
            if (cours != null)
            {
                _context.Cours.Remove(cours);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoursExists(int id)
        {
          return (_context.Cours?.Any(e => e.CoursId == id)).GetValueOrDefault();
        }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineSchoolWebApp.Data;
using OnlineSchoolWebApp.Models;

namespace OnlineSchoolWebApp.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Note.Include(n => n.Cours);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .Include(n => n.Cours)
                .FirstOrDefaultAsync(m => m.NoteId == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }


        public async Task<List<ApplicationUser>> DisplayStudents()
        {
            var roleId = await _context.Roles
                .Where(r => r.Name == "Student")
                .Select(r => r.Id)
                .FirstOrDefaultAsync();

            if (roleId == null)
            {
                // Handle the case where the "Student" role does not exist
                // e.g., display an error message or redirect to an error page
                return null;
            }

            var userIds = await _context.UserRoles
                .Where(ur => ur.RoleId == roleId)
                .Select(ur => ur.UserId)
                .ToListAsync();

            var students = await _context.Users
                .OfType<ApplicationUser>()
                .Where(u => userIds.Contains(u.Id))
                .Select(u => new ApplicationUser
                {
                    Id = u.Id,
                    FirstName = u.FirstName,
                    LastName = u.LastName
                })
                .ToListAsync();

            return students;
        }

        // GET: Notes/Create
        public async Task<IActionResult> Create()
        {
            ViewData["CoursId"] = new SelectList(_context.Cours, "CoursId", "Nom");
            var students = await DisplayStudents();
            ViewData["EtudiantId"] = new SelectList(students, "Id", "LastName");
            return View();
        }


        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoteId,NoteValue,NoteDesc,EtudiantId,CoursId")] Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CoursId"] = new SelectList(_context.Cours, "CoursId", "CoursId", note.CoursId);
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            ViewData["CoursId"] = new SelectList(_context.Cours, "CoursId", "CoursId", note.CoursId);
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoteId,NoteValue,NoteDesc,EtudiantId,CoursId")] Note note)
        {
            if (id != note.NoteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.NoteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CoursId"] = new SelectList(_context.Cours, "CoursId", "CoursId", note.CoursId);
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Note == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .Include(n => n.Cours)
                .FirstOrDefaultAsync(m => m.NoteId == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Note == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Note'  is null.");
            }
            var note = await _context.Note.FindAsync(id);
            if (note != null)
            {
                _context.Note.Remove(note);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
          return (_context.Note?.Any(e => e.NoteId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineSchool</title>
    <link rel="stylesheet" href="~/css/CssTheme.css" />
    <link rel="stylesheet" href="~/css/SideBar.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineSchoolWebApp.styles.css" asp-append-version="true" />
</head>

<body>
    <header>


        <div class="main-container d-flex">

            @* Side bar start*@
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <div class="sidebar" id="side_nav">
                    <div class="header-box px-2 pt-3 pb-4 d-flex justify-content-between">
                        <H2>
                            Welcome Admin
                        </H2>
                        <button class="btn d-md-none d-block close-btn px-1 py-0 text-white">
                            <i class="fal fa-stream"></i>
                        </button>
                    </div>

                    <ul class="list-unstyled px-2">
                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Etablissements" asp-action="Index">Etablissements</a>
                        </li>

                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="AnneeScolaires" asp-action="Index">Années scolaires</a>
                        </li>

                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Departements" asp-action="Index">Départements</a>
                        </li>

                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Niveaux" asp-action="Index">Niveaux</a>
                        </li>


                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Classes" asp-action="Index">Classes</a>
                        </li>

                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Cours" asp-action="Index">Cours</a>
                        </li>
                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Notes" asp-action="Index">Notes</a>
                        </li>
                    </ul>

                    <hr class="h-color mx-2">

                    <ul class="list-unstyled px-2">
                        <li> <H5>Membres</H5> </li>
                        <li class="">
                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Teacher" asp-action="DisplayTeachers">Enseignant</a>
                        </li>
                        </li>
                        @* <li class="">
                            <a href="#" class="text-decoration-none px-3 py-2 d-block">
                                <i class="fal fa-bell"></i>
                                Etudiants
                            </a>
                        </li> *@
                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="Student" asp-action="DisplayStudents">Etudiants</a>
                        </li>

                        <li class="">
                            <a class="text-decoration-none px-3 py-2 d-block" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                        </li>

                    </ul>
                </div> 
            }
            @* Side bar end*@





            <div class="content">
                @*    navbar start *@
                <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
                    <div class="container-fluid">

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                     
                    </div>
                    <partial name="_LoginPartial"></partial>
                </nav>
                @*    navbar end *@
                @* content start *@
                <div class="dashboard-content px-3 pt-4">
                    <h2 class="fs-5"> </h2>
                    <div class="container">

                        @RenderBody()

                    </div>
                </div>
                @* content end *@

            </div>
        </div>




    </header>








    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Identitytest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/SideBar.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>