Models/AnneeScolaire.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineSchoolWebApp.Models
{
    public class AnneeScolaire
    {
        public int AnneeScolaireId { get; set; }

        public DateTime DateDebut { get; set; }
        public DateTime DateFin { get; set; }


        public int? EtablissementId { get; set; }

    

        public virtual ICollection<Departement> Departements { get; set; } = new List<Departement>();

        public virtual Etablissement? Etablissement { get; set; }
    }
}

Models/Etablissement.cs
using System;
using System.Collections.Generic;

namespace OnlineSchoolWebApp.Models
{
    public class Etablissement
    {
        public int EtablissementId { get; set; }

        public string Nom { get; set; } = null!;

        public string Adresse { get; set; } = null!;

        public virtual ICollection<AnneeScolaire> AnneeScolaires { get; set; } = new List<AnneeScolaire>();
    }
}

Controllers/AnneeScolairesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineSchoolWebApp.Data;
using OnlineSchoolWebApp.Models;

namespace OnlineSchoolWebApp.Controllers
{
    public class AnneeScolairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnneeScolairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AnneeScolaires
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.AnneeScolaire.Include(a => a.Etablissement);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: AnneeScolaires/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AnneeScolaire == null)
            {
                return NotFound();
            }

            var anneeScolaire = await _context.AnneeScolaire
                .Include(a => a.Etablissement)
                .FirstOrDefaultAsync(m => m.AnneeScolaireId == id);
            if (anneeScolaire == null)
            {
                return NotFound();
            }

            return View(anneeScolaire);
        }

        // GET: AnneeScolaires/Create
        public IActionResult Create()
        {
            // display etablissement name 
            ViewData["EtablissementId"] = new SelectList(_context.Etablissement, "EtablissementId", "Nom");
            return View();
        }

        // POST: AnneeScolaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AnneeScolaireId,DateDebut,DateFin,EtablissementId")] AnneeScolaire anneeScolaire)
        {


            if (ModelState.IsValid)
            {
                _context.Add(anneeScolaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtablissementId"] = new SelectList(_context.Etablissement, "EtablissementId", "EtablissementId", anneeScolaire.EtablissementId);
            return View(anneeScolaire);
        }

        // GET: AnneeScolaires/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AnneeScolaire == null)
            {
                return NotFound();
            }

            var anneeScolaire = await _context.AnneeScolaire.FindAsync(id);
            if (anneeScolaire == null)
            {
                return NotFound();
            }
            ViewData["EtablissementId"] = new SelectList(_context.Etablissement, "EtablissementId", "EtablissementId", anneeScolaire.EtablissementId);
            return View(anneeScolaire);
        }

        // POST: AnneeScolaires/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AnneeScolaireId,DateDebut,DateFin,EtablissementId")] AnneeScolaire anneeScolaire)
        {
            if (id != anneeScolaire.AnneeScolaireId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anneeScolaire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnneeScolaireExists(anneeScolaire.AnneeScolaireId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtablissementId"] = new SelectList(_context.Etablissement, "EtablissementId", "EtablissementId", anneeScolaire.EtablissementId);
            return View(anneeScolaire);
        }

        // GET: AnneeScolaires/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AnneeScolaire == null)
            {
                return NotFound();
            }

            var anneeScolaire = await _context.AnneeScolaire
                .Include(a => a.Etablissement)
                .FirstOrDefaultAsync(m => m.AnneeScolaireId == id);
            if (anneeScolaire == null)
            {
                return NotFound();
            }

            return View(anneeScolaire);
        }

        // POST: AnneeScolaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AnneeScolaire == null)
            {
                return Problem("Entity set 'ApplicationDbContext.AnneeScolaire'  is null.");
            }
            var anneeScolaire = await _context.AnneeScolaire.FindAsync(id);
            if (anneeScolaire != null)
            {
                _context.AnneeScolaire.Remove(anneeScolaire);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnneeScolaireExists(int id)
        {
          return (_context.AnneeScolaire?.Any(e => e.AnneeScolaireId == id)).GetValueOrDefault();
        }


        //public async Task<IActionResult> GetDepartmentByYearPartial(int? id)
        //{
        //    if (id == null || _context.AnneeScolaire == null)
        //    {
        //        return NotFound();
        //    }

        //    var schoolYear = await _context.AnneeScolaire
        //        .Include(e => e.Departements)
        //        .FirstOrDefaultAsync(m => m.AnneeScolaireId == id);

        //    if (schoolYear == null)
        //    {
        //        return NotFound();
        //    }

        //    Debug.WriteLine("Departements in schoolYear:");
        //    foreach (var department in schoolYear.Departements)
        //    {
        //        Debug.WriteLine(department.Nom);
        //    }
        //    return PartialView("_DepartmentsPartial", schoolYear.Departements.ToList());
        //}


        public async Task<IActionResult> YourAction(int? id)
        {
            if (id == null || _context.AnneeScolaire == null)
            {
                return NotFound();
            }

            var schoolYear = await _context.AnneeScolaire
                .Include(e => e.Departements)
                .FirstOrDefaultAsync(m => m.AnneeScolaireId == id);

            if (schoolYear == null)
            {
                return NotFound();
            }

            var viewModel = new SchoolViewModel
            {
                AnneeScolaire = schoolYear,
                Departements = schoolYear.Departements.ToList()
            };
            // Add this for debugging
            Debug.WriteLine($"Number of Departements: {viewModel.Departements.Count}");

            return View(viewModel);
        }



    }
    public class SchoolViewModel
    {
        public AnneeScolaire AnneeScolaire { get; set; }
        public List<Departement> Departements { get; set; }
    }


}

Controllers/EtablissementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineSchoolWebApp.Data;
using OnlineSchoolWebApp.Models;

namespace OnlineSchoolWebApp.Controllers
{
    public class EtablissementsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EtablissementsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Etablissements
        public async Task<IActionResult> Index()
        {
              return _context.Etablissement != null ? 
                          View(await _context.Etablissement.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Etablissement'  is null.");
        }

        // GET: Etablissements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Etablissement == null)
            {
                return NotFound();
            }

            var etablissement = await _context.Etablissement
                .FirstOrDefaultAsync(m => m.EtablissementId == id);
            if (etablissement == null)
            {
                return NotFound();
            }

            return View(etablissement);
        }

        // GET: Etablissements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Etablissements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EtablissementId,Nom,Adresse")] Etablissement etablissement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(etablissement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(etablissement);
        }

        // GET: Etablissements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Etablissement == null)
            {
                return NotFound();
            }

            var etablissement = await _context.Etablissement.FindAsync(id);
            if (etablissement == null)
            {
                return NotFound();
            }
            return View(etablissement);
        }

        // POST: Etablissements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EtablissementId,Nom,Adresse")] Etablissement etablissement)
        {
            if (id != etablissement.EtablissementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(etablissement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EtablissementExists(etablissement.EtablissementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(etablissement);
        }

        // GET: Etablissements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Etablissement == null)
            {
                return NotFound();
            }

            var etablissement = await _context.Etablissement
                .FirstOrDefaultAsync(m => m.EtablissementId == id);
            if (etablissement == null)
            {
                return NotFound();
            }

            return View(etablissement);
        }

        // POST: Etablissements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Etablissement == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Etablissement'  is null.");
            }
            var etablissement = await _context.Etablissement.FindAsync(id);
            if (etablissement != null)
            {
                _context.Etablissement.Remove(etablissement);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EtablissementExists(int id)
        {
          return (_context.Etablissement?.Any(e => e.EtablissementId == id)).GetValueOrDefault();
        }



        //Display all school years that belongs to a school 
        public async Task<IActionResult> AnneeScolaires(int? id)
        {
            if (id == null || _context.Etablissement == null)
            {
                return NotFound();
            }

            var etablissement = await _context.Etablissement
                .Include(e => e.AnneeScolaires) // Include related AnneeScolaires
                .FirstOrDefaultAsync(m => m.EtablissementId == id);

            if (etablissement == null)
            {
                return NotFound();
            }

            return View(etablissement.AnneeScolaires.ToList());
        }



    }
}

Views/Etablissements/AnneeScolaires.cshtml
@model List<AnneeScolaire>

<h1>Annee Scolaires</h1>

<table class="table">
    <thead>
        <tr>
            <th>Date Début</th>
            <th>Date Fin</th>
        </tr>
       
    </thead>
    <tbody>
        @foreach (var anneeScolaire in Model)
        {
            <tr>
                <td>@Html.ActionLink(anneeScolaire.DateDebut.ToString(), "Details", "AnneeScolaires", new { id = anneeScolaire.AnneeScolaireId }, null)</td>
             
                <td>@Html.ActionLink(anneeScolaire.DateFin.ToString(), "Details", "AnneeScolaires", new { id = anneeScolaire.AnneeScolaireId }, null)</td>
             
            </tr>
        }
    </tbody>
</table>

Views/Etablissements/Create.cshtml
@model OnlineSchoolWebApp.Models.Etablissement

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Etablissement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Etablissements/Delete.cshtml
@model OnlineSchoolWebApp.Models.Etablissement

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Etablissement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EtablissementId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Etablissements/Details.cshtml
@model OnlineSchoolWebApp.Models.Etablissement

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Etablissement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EtablissementId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Etablissements/Edit.cshtml
@model OnlineSchoolWebApp.Models.Etablissement

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Etablissement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EtablissementId" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Etablissements/Index.cshtml
@model IEnumerable<OnlineSchoolWebApp.Models.Etablissement>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th>Années Scolaires</th> <!-- New column for AnneeScolaires link -->
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adresse)
                </td>
               
                <td>
                    <a asp-action="AnneeScolaires" asp-route-id="@item.EtablissementId">Annee Scolaires</a>
                </td>
                <td>
                    <form asp-action="Edit" asp-route-id="@item.EtablissementId" method="get">
                        <button type="submit" class="btn btn-outline-secondary">Modifier</button>
                    </form>
                </td>
            
            
                <td>
                    <form asp-action="Details" asp-route-id="@item.EtablissementId" method="get">
                        <button type="submit" class="btn btn-outline-success">Détails</button>
                    </form>
                </td>
            
           
                <td>
                    <form asp-action="Delete" asp-route-id="@item.EtablissementId" method="get">
                        <button type="submit" class="btn btn-outline-danger">Supprimer</button>
                    </form>

                </td>
            </tr>
        }
    </tbody>
</table>